version: '3'

services:
  db-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker 
      - POSTGRESQL_PASSWORD=ps123 
      - POSTGRESQL_DATABASE=languagemanager
    